// JOBS
export const FETCH_JOBS_REQUEST = "[JOBS] FETCH_JOBS_REQUEST";
export const FETCH_JOBS_SUCCESS = "[JOBS] FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_FAILURE = "[JOBS] FETCH_JOBS_FAILURE";
export const CLEAR_JOBS = "[JOBS] CLEAR_JOBS";

//SINGLE JOB
export const FETCH_JOB_REQUEST = "[JOB] FETCH_JOB_REQUEST";
export const FETCH_JOB_SUCCESS = "[JOB] FETCH_JOB_SUCCESS";
export const FETCH_JOB_FAILURE = "[JOB] FETCH_JOB_FAILURE";

// THEME
export const TOGGLE_THEME = "[THEME] TOGGLE_THEME";

// FILTERS
export const FILTER_POSITIONS = "[FILTER] FILTER_POSITIONS";

// PAGE
export const CHANGE_PAGE = "[PAGE] CHANGE_PAGE";

// MOBILE/PC
export const MOBILE_BROWSER = "[BROWSER] MOBILE_BROWSER";

// LOCATION
export const LOCATION_ON = "[LOCATION] LOCATION_ON";
